//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace contactProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class emailTBL
    {
        public int Id { get; set; }
        public int cID { get; set; }
        public string email { get; set; }
    
        public virtual contactTBL contactTBL { get; set; }
    }
}
